### PR TITLE
Remove virtual calls in dtors

### LINKED ISSUE #99: [Issue]: Fix clang-tidy virtual destructor issues
### Problem Description

Building with clang-tidy reports a couple of problems with making virtual calls in destructors. This is due to the way we are using mocks in the tests.

```
/.../hipfile/src/amd_detail/buffer.cpp:169:13: warning: Call to virtual method 'BufferMap::deregisterBuffer' during destruction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall]
  169 |             deregisterBuffer(ptr);
      |             ^~~~~~~~~~~~~~~~~~~~~
/.../hipfile/src/amd_detail/buffer.cpp:169:13: note: Call to virtual method 'BufferMap::deregisterBuffer' during destruction bypasses virtual dispatch
  169 |             deregisterBuffer(ptr);
      |             ^~~~~~~~~~~~~~~~~~~~~
/.../hipfile/src/amd_detail/file.cpp:158:13: warning: Call to virtual method 'FileMap::deregisterFile' during destruction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall]
  158 |             deregisterFile(fh);
      |             ^~~~~~~~~~~~~~~~~~
/.../hipfile/src/amd_detail/file.cpp:158:13: note: Call to virtual method 'FileMap::deregisterFile' during destruction bypasses virtual dispatch
  158 |             deregisterFile(fh);
      |             ^~~~~~~~~~~~~~~~~~
```

### Operating System

Any

### CPU

Any

### GPU

Any

### ROCm Version

Any

### ROCm Component

_No response_

### Steps to Reproduce

Build with clang-tidy (AIS_USE_CLANG_TIDY=ON)

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by derobins**
clang-tidy complains about using virtual calls in the FileMap and BufferMap destructors. The virtual calls in question attempt to shut down the map objects, which is unnecessary, as the maps contain shared pointers that will be cleaned when they go out of scope.

The functionality that we retained is complaining about any in-use File or Buffer objects when the associated maps are shut down. Previously, this would result in exit() being called in debug builds and silently ignoring the problem in release builds. The new behavior is to create syslog messages in all builds (like our Stream class).

Fixes #99

### CODE REVIEW

**Comment by derobins** [comment]
I'm not opposed to Copilot's suggestions. We should make all the classes uniform, though (i.e., changes here should also be made in Stream's dtor.

File: hipfile/src/amd_detail/file.cpp [hunk 1]
```diff
@@ -147,27 +148,14 @@ FileMap::clear()
...
-        transform(from_fh.begin(), from_fh.end(), std::back_inserter(file_handles),
-                  [](const auto &pair) { return pair.first; });
-
-        for (const auto &fh : file_handles) {
-            // NOLINTNEXTLINE(clang-analyzer-optin.cplusplus.VirtualCall)
-            deregisterFile(fh);
+    // Complain in the logs if we're shutting down a FileMap
+    // with files that are still in use.
+    for (const auto &p : from_fh) {
+        if (p.second.use_count() > 1) {
```
Comment (jordan-turbofish) [inline hipfile/src/amd_detail/file.cpp]: This needs to be `> 2` because each shared_ptr is in two maps.

Comment (derobins) [reply hipfile/src/amd_detail/file.cpp]: Fixed

**Comment by kurtmcmillan** [comment]
> I'm not opposed to Copilot's suggestions. We should make all the classes uniform, though (i.e., changes here should also be made in Stream's dtor.

It might be useful to log the file descriptor of each file still in use and the buffer pointer for each buffer still in use.

**Comment by derobins** [comment]
> > I'm not opposed to Copilot's suggestions. We should make all the classes uniform, though (i.e., changes here should also be made in Stream's dtor.
> 
> It might be useful to log the file descriptor of each file still in use and the buffer pointer for each buffer still in use.

I thought about something like that, but how useful is that information?

**Comment by kurtmcmillan** [comment]
> > > I'm not opposed to Copilot's suggestions. We should make all the classes uniform, though (i.e., changes here should also be made in Stream's dtor.
> > 
> > 
> > It might be useful to log the file descriptor of each file still in use and the buffer pointer for each buffer still in use.
> 
> I thought about something like that, but how useful is that information?

Good point. It may not be useful on its own. Perhaps when we have more logging. For now I guess it would be good enough just to indicate that there were outstanding operations on files/buffers.

**Review by kurtmcmillan — APPROVED** [review]

**Review by jordan-turbofish — APPROVED** [review]

**Review by riley-dixon — APPROVED** [review]
